sudo: false  # use new container infrastructure on Travis CI

language: python

python: 2.7

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c conda conda-env
  - conda info -a  # Useful for debugging any issues with conda

install:
  - conda env create  # create env using NILMTK's environment.yml
  - source activate nilmtk-env
  - git clone https://github.com/nilmtk/nilm_metadata/
  - cd nilm_metadata; python setup.py develop; cd ..  
  - pip install -e 'git+https://github.com/nilmtk/nilmtk.git#egg=nilmtk'

script:
  - python -c 'from nilmtk.utils import show_versions; show_versions()'
  - nosetests --with-coverage

after_success:
  - coveralls

after_script:
  - source deactivate
