name: nilmtk-env
dependencies:
- python=2.7
- Cython>=0.19.1
- bottleneck>=0.6.0
- numpy>=1.8.0
- numexpr>=2.2.2
- pytables
- pandas>=0.17.1
- matplotlib
- networkx
- scipy
- scikit-learn>=0.14
- ipython
- six
- psycopg2
- nose
- sh
- coverage
- pip
- pip:
    - coveralls
    - hmmlearn==0.1.1
